### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by AllanChen** [darknessomi/360WiFi-Linux#1]
直接make 之后，找不到 modules
![screen shot 2015-11-17 at 6 39 04 pm](https://cloud.githubusercontent.com/assets/1639667/11209173/91a68b72-8d5a-11e5-91df-c87bee290efe.png)

**Comment by bluarry** [comment]
Maybe you need to install build-essential and linux-headers-generic before you start.

**Comment by luoyedaren** [comment]
chenghai@debian:~/apps/360wifi$ sudo make
make -C tools
make[1]: 进入目录“/home/chenghai/apps/360wifi/tools”
gcc -g bin2h.c -o bin2h
make[1]: 离开目录“/home/chenghai/apps/360wifi/tools”
/home/chenghai/apps/360wifi/tools/bin2h
cp -f os/linux/Makefile.6 /home/chenghai/apps/360wifi/os/linux/Makefile
make -C /lib/modules/4.19.0-5-amd64/build SUBDIRS=/home/chenghai/apps/360wifi/os/linux modules
make[1]: 进入目录“/usr/src/linux-headers-4.19.0-5-amd64”
  CC [M]  /home/chenghai/apps/360wifi/os/linux/../../os/linux/rt_profile.o
/home/chenghai/apps/360wifi/os/linux/../../os/linux/rt_profile.c: In function ‘announce_802_3_packet’:
/home/chenghai/apps/360wifi/os/linux/../../os/linux/rt_profile.c:331:16: warning: unused variable ‘pAd’ [-Wunused-variable]
  RTMP_ADAPTER *pAd = (RTMP_ADAPTER *)pAdSrc;
                ^~~
In file included from /home/chenghai/apps/360wifi/include/rtmp_os.h:44,
                 from /home/chenghai/apps/360wifi/include/rtmp_comm.h:75,
                 from /home/chenghai/apps/360wifi/include/rt_config.h:33,
                 from /home/chenghai/apps/360wifi/os/linux/../../os/linux/rt_profile.c:28:
/home/chenghai/apps/360wifi/os/linux/../../os/linux/rt_profile.c: In function ‘STA_MonPktSend’:
/home/chenghai/apps/360wifi/os/linux/../../os/linux/rt_profile.c:399:35: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘long unsigned int’ [-Wformat=]
         DBGPRINT(RT_DEBUG_ERROR, ("%s : Size is too large! (%d)\n", __FUNCTION__, pRxBlk->DataSize + sizeof(wlan_ng_prism2_header)));
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/chenghai/apps/360wifi/include/os/rt_linux.h:661:16: note: in definition of macro ‘DBGPRINT_RAW’
         printk Fmt;               \
                ^~~
/home/chenghai/apps/360wifi/os/linux/../../os/linux/rt_profile.c:399:9: note: in expansion of macro ‘DBGPRINT’
         DBGPRINT(RT_DEBUG_ERROR, ("%s : Size is too large! (%d)\n", __FUNCTION__, pRxBlk->DataSize + sizeof(wlan_ng_prism2_header)));
         ^~~~~~~~
  CC [M]  /home/chenghai/apps/360wifi/os/linux/../../sta/assoc.o
  CC [M]  /home/chenghai/apps/360wifi/os/linux/../../sta/auth.o
  CC [M]  /home/chenghai/apps/360wifi/os/linux/../../sta/auth_rsp.o
  CC [M]  /home/chenghai/apps/360wifi/os/linux/../../sta/sync.o
/home/chenghai/apps/360wifi/os/linux/../../sta/sync.c: In function ‘PeerBeacon’:
/home/chenghai/apps/360wifi/os/linux/../../sta/sync.c:2180:12: error: passing argument 8 of ‘StaAddMacTableEntry’ from incompatible pointer type [-Werror=incompatible-pointer-types]
            ie_list,
            ^~~~~~~
In file included from /home/chenghai/apps/360wifi/include/rt_config.h:59,
                 from /home/chenghai/apps/360wifi/os/linux/../../sta/sync.c:28:
/home/chenghai/apps/360wifi/include/rtmp.h:7900:15: note: expected ‘IE_LISTS *’ {aka ‘struct _IE_lists *’} but argument is of type ‘BCN_IE_LIST *’ {aka ‘struct _bcn_ie_list *’}
  IN IE_LISTS *ie_list,
     ~~~~~~~~~~^~~~~~~
cc1: some warnings being treated as errors
make[4]: *** [/usr/src/linux-headers-4.19.0-5-common/scripts/Makefile.build:309：/home/chenghai/apps/360wifi/os/linux/../../sta/sync.o] 错误 1
make[3]: *** [/usr/src/linux-headers-4.19.0-5-common/Makefile:1539：_module_/home/chenghai/apps/360wifi/os/linux] 错误 2
make[2]: *** [Makefile:146：sub-make] 错误 2
make[1]: *** [Makefile:8：all] 错误 2
make[1]: 离开目录“/usr/src/linux-headers-4.19.0-5-amd64”
make: *** [Makefile:395：LINUX] 错误 2

**Comment by Direct-A** [comment]
咋解决的，我centos也编译报错
```
[root@879c0d2d67c6 Downloads]# make
make -C tools
make[1]: Entering directory `/root/Downloads/tools'
gcc -g bin2h.c -o bin2h
make[1]: Leaving directory `/root/Downloads/tools'
/root/Downloads/tools/bin2h
cp -f os/linux/Makefile.6 /root/Downloads/os/linux/Makefile
make -C /lib/modules/5.10.52-1-lts/build SUBDIRS=/root/Downloads/os/linux modules
make: *** /lib/modules/5.10.52-1-lts/build: No such file or directory.  Stop.
make: *** [LINUX] Error 2
```

**Comment by Direct-A** [comment]
> 咋解决的，我centos也编译报错
> 
> ```
> [root@879c0d2d67c6 Downloads]# make
> make -C tools
> make[1]: Entering directory `/root/Downloads/tools'
> gcc -g bin2h.c -o bin2h
> make[1]: Leaving directory `/root/Downloads/tools'
> /root/Downloads/tools/bin2h
> cp -f os/linux/Makefile.6 /root/Downloads/os/linux/Makefile
> make -C /lib/modules/5.10.52-1-lts/build SUBDIRS=/root/Downloads/os/linux modules
> make: *** /lib/modules/5.10.52-1-lts/build: No such file or directory.  Stop.
> make: *** [LINUX] Error 2
> ```

This is a placeholder repo for the Linux driver for MediaTek MT7601U USB dongle. The driver was written from scratch based on the vendor GPL-driver. Unlike the vendor driver it uses modern Linux WiFi infrastructure and should work flawlessly with NetworkManager, wicd, wpa_supplicant and such. This driver was merged into mainline and is part of official Linux kernel since version v4.2 (August 2015).

Please report any issues upstream to the Linux Wireless community. This repo is no longer used.

现在已经可以直接使了😂
